Repository thoov/ember-websockets, pull requests merged in 2022-05, with the labels that each got.

#201 fix to retrieve environment config for socket.io use case
  config/environment.js
  index.js
  server/mocks/socketio.js
  tests/acceptance/socketio-test.js
  tests/dummy/app/controllers/socketio/simple.js
  tests/dummy/app/templates/socketio/simple.hbs
Labels: bug

#224 ember-cli 4.3
  .ember-cli
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .prettierignore
  CONTRIBUTING.md
  config/ember-try.js
  package.json
  tests/dummy/app/index.html
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/helpers/index.js
  tests/index.html
  yarn.lock
Labels: internal

#228 Update socket.io to 3.x
  addon/helpers/socketio-proxy.js
  index.js
  package.json
  yarn.lock
Labels: breaking

#229 Add back urijs to support relative urls
  addon/helpers.js
  ember-cli-build.js
  index.js
  package.json
  vendor/shims/mock-socket.js
  yarn.lock
Labels: bug

#230 Remove unnecessary vendor funnels
  index.js
  package.json
  yarn.lock
Labels: enhancement
